const btnSubmit = document.querySelector(".btn-submit")
const msgSuccess = document.querySelector('.msg-success')
const errorCheckbox = document.querySelector('.error-checkbox')
const errorMessage = document.querySelector(".error-message")
const invalidEmail = document.querySelector(".email-invalid")
const errorRadio = document.querySelector(".error-radio")
const errorEmail = document.querySelector(".error-email")
const errorLname = document.querySelector(".error-lname")
const errorFname = document.querySelector(".error-fname")
const inputFname = document.querySelector("#fname")
const inputLname = document.querySelector("#lname")
const inputEmail = document.querySelector("#email")
const btnRados = document.querySelectorAll("input[type='radio']")
const textArea = document.querySelector("#msg-area")
const checkbox = document.querySelector("#checkbox-cosent")

